# Generated by Django 4.1.6 on 2023-02-17 22:32

from django.db import migrations
from django.contrib.auth.management import create_permissions
from django.contrib.auth.models import Group, Permission

def createGroups(apps, schema_editor):
    groups = ["User", "Employee", "Manager"]
    for groupName in groups:
        Group.objects.create(name=groupName)

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(createGroups),
    ]
