# Generated by Django 4.1.2 on 2023-02-21 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_car_carreservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerId', models.IntegerField()),
                ('carId', models.IntegerField()),
                ('assigned', models.BooleanField(default=False)),
            ],
        ),
    ]
