# Generated by Django 4.1.1 on 2023-03-30 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_serviceticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='carreservation',
            name='insurance',
            field=models.BooleanField(default=False),
        ),
    ]
